### ISSUE TITLE
Support for proxy?

### ISSUE THREAD

**Issue by twuytens** [splunk/github-audit-log-monitoring-add-on-for-splunk#11]
Hi,

We want to use this app on our on-premise HF to pull the audit logs from our github.com enterprise and orgs. Our HF is behind a corporate proxy, but we cannot seem to find any option to provide the proxy setup for this modular input app?

Could you tell me if this is supported, and if not, if it is part of your roadmap to support this in the near future?

Thanks!

**Comment by Link-** [comment]
Heyy @twuytens thank you for sharing this request. I've shared with the team that the recommended approach is to use [audit log streaming](https://docs.github.com/en/enterprise-cloud@latest/admin/user-management/managing-organizations-in-your-enterprise/streaming-the-audit-logs-for-organizations-in-your-enterprise-account).

If that turns out to be an impossibility to implement on your end, I can make changes to accommodate proxies.

**Comment by njaiswal27** [comment]
I do agree with @twuytens if support for proxy is available it would be great, this app can add more value, we need it this feature asap

**Comment by Link-** [comment]
@derkkila - we might want to invest in adding proxy support here

**Comment by derkkila-splunk** [comment]
Proxy support isn't available in the current version, but I am adding it to the backlog and will see what is needed to add it. So I'm going to leave this open for future updates.

**Comment by njaiswal27** [comment]
@derkkila-splunk Thank you for adding it action item. We would really appreciate if you get this feature enhancement as early as possible. We look forward for a fix soon.

**Comment by derkkila-splunk** [comment]
@njaiswal27 An update to a different GitHub add-on has been released to now support GitHub Cloud and it includes proxy support. With that, this add-on is going to be sunset.

Download and use this add-on: https://splunkbase.splunk.com/app/6254/

**Comment by njaiswal27** [comment]
@derkkila-splunk Thank you for addressing this issue, I will be deploy the new changes and verify it.
